# Generated by Django 4.0.3 on 2022-03-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyHackWiFiAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='User',
        ),
    ]
